#!/usr/bin/env python3
"""Stage-4 exporter — PG she_catalog → canonical SHE ABox TTL (SSOT=PG, CAT-4/F13).

PG `she_catalog`의 SHE 패턴을 온톨로지 ABox(she:SituationalHazardPattern)로 내보내
Fuseki/리즈너에 정합시킨다. scope:
- markers (기본): OWA→CWA L2 보강 37패턴(marker owacwa-*-20260608)만
  → kosha-instances-she-l2tune.ttl  (기존 surgical 동기화 경로, 무변경)
- active: 서빙 status(approved_auto/approved_manual) 전량
  → kosha-instances-she-full.ttl  (전량 export — legacy 965 TTL 퇴역의 토대)

코드→IRI는 code_iri_mapper SSOT(F15 이중구현 해소): 3축(accident/agent/context)은
fine 보존 emit(fine_iri_fragment; taxonomy fine⊑canonical이 rollup 담당) → canonical
fold(iri_fragment) 순으로 해석하고, 교차축/미지 코드는 silent skip 대신 리포트.
잔여 차원(ppe/env/activity/agent_state/temporal)은 결정적 UPPER_SNAKE→PascalCase.
최종 안전망 = TBox 존재검증(gen_she_abox.py defined_facets 미러; gap>0 → exit 1).

사용: python export_she_catalog_to_abox.py [--scope markers|active] [--out PATH] [--apply]
     (기본 dry-run; gap 0이어야 기록 가능. DSN은 env PG_DSN > DATABASE_URL > 로컬 기본값)
"""
from __future__ import annotations
import argparse
import json
import os
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

import psycopg2
from rdflib import Graph, RDF, RDFS, OWL

HERE = Path(__file__).resolve()
ROOT = HERE.parents[3]  # export-scripts/ -> 04-ontology-export/ -> data-team/ -> repo root
ONT = ROOT / "ontology-team" / "06-reasoning" / "ontology"
sys.path.insert(0, str(ONT / "assembly"))
import manifest_source as MS  # noqa: E402

# code_iri_mapper SSOT (F15) — canonical-code-vocabulary.json 파생 결정적 변환.
sys.path.insert(0, str(ROOT / "serving-team" / "08-app" / "backend" / "app" / "integrations"))
import code_iri_mapper as CIM  # noqa: E402

OUT_BY_SCOPE = {
    "markers": ONT / "kosha-instances-she-l2tune.ttl",
    "active": ONT / "kosha-instances-she-full.ttl",
}
PG_DSN = (os.environ.get("PG_DSN") or os.environ.get("DATABASE_URL")
          or "dbname=kosha user=kosha password=1229 host=localhost port=5432")
MARKERS = ["owacwa-l2tune-20260608", "owacwa-foodgas-20260608", "owacwa-ind-20260608"]

NS = {
    "ctx":   "https://cashtoss.info/ontology/risk/context#",
    "haz":   "https://cashtoss.info/ontology/risk/hazard#",
    "agent": "https://cashtoss.info/ontology/risk/agent#",
}
FACET_NS = tuple(NS.values())

# dim -> (she property local, prefix)
DIM_AXIS = {
    "work_activity":   ("hasWorkActivity",   "ctx"),
    "work_context":    ("hasWorkContext",    "ctx"),
    "hazardous_agent": ("hasHazardousAgent", "agent"),
    "accident_type":   ("hasAccidentType",   "haz"),
    "agent_state":     ("hasAgentState",     "ctx"),
    "ppe_state":       ("hasPPEState",       "ctx"),
    "environmental":   ("hasEnvironmental",  "ctx"),
    "temporal_stage":  ("hasTemporalStage",  "ctx"),
}
# OTHER -> Other{Axis} class (기존 컨벤션 보존). wc/at/ha의 OTHER는 OWL 미정의라 skip.
OTHER_CLASS = {
    "work_activity": "OtherActivity", "agent_state": "OtherAgentState",
    "ppe_state": "OtherPPEState", "environmental": "OtherEnvironmental",
    "temporal_stage": "OtherTemporal",
}
SKIP_OTHER = {"work_context", "accident_type", "hazardous_agent"}

HEADER_BY_SCOPE = {
    "markers": ("# kosha-instances-she-l2tune.ttl — OWA→CWA L2 보강 SHE 패턴 ABox\n"
                "# 소스: PG she_catalog WHERE source_prompt_hash IN (owacwa-l2tune/foodgas/ind-20260608)\n"),
    "active": ("# kosha-instances-she-full.ttl — PG she_catalog 서빙 전량 SHE ABox (SSOT=PG)\n"
               "# 소스: PG she_catalog WHERE status IN (approved_auto, approved_manual)\n"),
}
PREFIXES = """# (AUTO-GENERATED by data-team/04-ontology-export/export-scripts/export_she_catalog_to_abox.py — 수동편집 금지)
@prefix risk:  <https://cashtoss.info/ontology/risk#> .
@prefix she:   <https://cashtoss.info/ontology/risk/situation#> .
@prefix sr:    <https://cashtoss.info/ontology/sr#> .
@prefix ctx:   <https://cashtoss.info/ontology/risk/context#> .
@prefix agent: <https://cashtoss.info/ontology/risk/agent#> .
@prefix haz:   <https://cashtoss.info/ontology/risk/hazard#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
"""


def snake_to_pascal(code: str) -> str:
    return "".join(seg.capitalize() for seg in code.split("_"))


# 3축은 code_iri_mapper SSOT 해석 경로 사용 (F15 — fine 보존 우선, canonical fold 차선,
# TBox-검증 예외 차차선). 해석 실패 수집: {(dim, code): count} — silent skip 금지.
_MAIN_AXES = {"accident_type", "hazardous_agent", "work_context"}
UNRESOLVED: dict[tuple[str, str], int] = {}
TBOX_EXCEPTIONS: dict[tuple[str, str], int] = {}
# main()이 defined_facets()로 채움 — TBox-검증 예외 단계의 allowlist.
DEFINED: set = set()


def feature_iri(dim: str, value):
    if not value:
        return None
    if value == "OTHER":
        if dim in SKIP_OTHER:
            return None
        frag = OTHER_CLASS.get(dim)
        return f"{DIM_AXIS[dim][1]}:{frag}" if frag else None
    if dim in _MAIN_AXES:
        frag = CIM.fine_iri_fragment(dim, value) or CIM.iri_fragment(dim, value)
        if frag is None:
            # SSOT 미해석(교차축/미지)이라도 TBox에 의도적으로 큐레이션된 클래스가
            # 있으면 신뢰(예: agent:OxygenDeficiency — kosha-facet-l2tune-patch.ttl,
            # haz:OxygenDeficiency(사고축)와 개념 병존하는 문서화된 결정). TBox 부재면
            # per-dim property 미발행(축 disjoint 보호) + 리포트.
            raw = snake_to_pascal(value)
            prefix = DIM_AXIS[dim][1]
            if NS[prefix] + raw in DEFINED:
                TBOX_EXCEPTIONS[(dim, value)] = TBOX_EXCEPTIONS.get((dim, value), 0) + 1
                return f"{prefix}:{raw}"
            UNRESOLVED[(dim, value)] = UNRESOLVED.get((dim, value), 0) + 1
            return None
        return f"{DIM_AXIS[dim][1]}:{frag}"
    return f"{DIM_AXIS[dim][1]}:{snake_to_pascal(value)}"


def expand(curie: str) -> str:
    prefix, frag = curie.split(":", 1)
    return NS[prefix] + frag


def escape_ttl(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def defined_facets() -> set:
    """serving profile의 비-instances 파일에 정의된 haz/agent/ctx 클래스·개체 (gen_she_abox 미러)."""
    defined = set()
    for e in MS.by_profile("serving"):
        if "instances" in e["file"]:
            continue
        g = Graph()
        g.parse(str(ONT / e["file"]), format=("xml" if e["format"] == "xml" else "turtle"))
        for s in g.subjects(RDF.type, OWL.Class):
            defined.add(str(s))
        for s in g.subjects(RDF.type, OWL.NamedIndividual):
            defined.add(str(s))
        for s, _o in g.subject_objects(RDFS.subClassOf):
            defined.add(str(s))
    return defined


def fetch_patterns(scope: str) -> list[dict]:
    conn = psycopg2.connect(PG_DSN)
    cur = conn.cursor()
    if scope == "markers":
        where = "c.source_prompt_hash = ANY(%s)"
        params = (MARKERS,)
    else:  # active — 서빙 카탈로그 전량 (SSOT=PG)
        where = "c.status IN ('approved_auto', 'approved_manual')"
        params = ()
    cur.execute(
        f"""
        SELECT c.she_id, c.name, c.features, c.visual_triggers, c.source_sr_ids,
               COALESCE(json_agg(DISTINCT m.ci_id) FILTER (WHERE m.ci_id IS NOT NULL), '[]'::json) AS ci_ids
        FROM she_catalog c
        LEFT JOIN she_ci_mapping m ON m.she_id = c.she_id
        WHERE {where}
        GROUP BY c.she_id, c.name, c.features, c.visual_triggers, c.source_sr_ids
        ORDER BY c.she_id
        """,
        params,
    )
    rows = []
    for she_id, name, features, vts, srs, ci_ids in cur.fetchall():
        def _j(v, default):
            if v is None:
                return default
            return v if not isinstance(v, str) else json.loads(v)
        rows.append({
            "she_id": she_id, "name": name or "",
            "features": _j(features, {}), "visual_triggers": _j(vts, []),
            "source_sr_ids": _j(srs, []), "ci_ids": _j(ci_ids, []),
        })
    cur.close()
    conn.close()
    return rows


def vt_texts(vts, fallback: str) -> list[str]:
    out = []
    for item in vts or []:
        v = item.get("text") if isinstance(item, dict) else str(item)
        if v and v.strip():
            out.append(v.strip())
    return out or ([fallback] if fallback else [])


def she_block(p: dict):
    she_id = p["she_id"]
    lines = [f"she:{she_id} a she:SituationalHazardPattern ;"]
    if p["name"]:
        lines.append(f'    rdfs:label "{escape_ttl(p["name"])}"@ko ;')
    feats = []
    for dim, val in (p["features"] or {}).items():
        if dim not in DIM_AXIS:
            continue
        iri = feature_iri(dim, val)
        if iri is None:
            continue
        lines.append(f"    she:{DIM_AXIS[dim][0]} {iri} ;")
        feats.append(iri)
    for iri in sorted(set(feats)):
        lines.append(f"    risk:hasFeature {iri} ;")
    triggers = vt_texts(p["visual_triggers"], p["name"])
    tids = [f"VT-{she_id}-{i + 1}" for i in range(len(triggers))]
    for tid in tids:
        lines.append(f"    she:hasVisualTrigger she:{tid} ;")
    srs = [f"sr:{s}" for s in p["source_sr_ids"]]
    if srs:
        lines.append(f"    she:appliesSR {', '.join(srs)} .")
    else:
        lines[-1] = lines[-1].rstrip(" ;") + " ."
    blocks = ["\n".join(lines)]
    for tid, txt in zip(tids, triggers):
        blocks.append(f'she:{tid} a she:VisualTrigger ;\n    she:triggerText "{escape_ttl(txt)}"@ko .')
    return "\n\n".join(blocks), feats


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="파일 기록(기본 dry-run)")
    ap.add_argument("--scope", choices=["markers", "active"], default="markers",
                    help="markers=L2 보강 37패턴(기본) / active=서빙 카탈로그 전량")
    ap.add_argument("--out", type=Path, default=None, help="출력 경로 override")
    args = ap.parse_args()
    out_path = args.out or OUT_BY_SCOPE[args.scope]

    # TBox-검증 예외 단계(feature_iri)가 참조하므로 패턴 처리 전에 로드.
    defined = defined_facets()
    DEFINED.update(defined)

    pats = fetch_patterns(args.scope)
    blocks, used = [], set()
    for p in pats:
        block, feats = she_block(p)
        blocks.append(block)
        used.update(expand(f) for f in feats)

    gaps = sorted(u for u in used if u.startswith(FACET_NS) and u not in defined)
    print(f"  scope={args.scope} · 패턴 {len(pats)} · 사용 facet IRI {len(used)} (TBox gap {len(gaps)})")
    if TBOX_EXCEPTIONS:
        print(f"[NOTE] SSOT 미해석이나 TBox 큐레이션 클래스로 emit {len(TBOX_EXCEPTIONS)}종:",
              ", ".join(f"{d}={c} ×{n}" for (d, c), n in sorted(TBOX_EXCEPTIONS.items())))
    if UNRESOLVED:
        total = sum(UNRESOLVED.values())
        print(f"[WARN] 3축 SSOT 해석 실패(교차축/미지) {len(UNRESOLVED)}종 {total}회 — "
              f"per-dim property 미발행(축 disjoint 보호), 카탈로그 데이터 정정 대상:",
              file=sys.stderr)
        for (dim, code), n in sorted(UNRESOLVED.items(), key=lambda kv: -kv[1])[:20]:
            print(f"    {dim}={code} ×{n}", file=sys.stderr)
    if gaps:
        print("[FAIL] TBox에 정의 없는 facet 코드(gap):", file=sys.stderr)
        for g in gaps:
            print("   ", g, file=sys.stderr)
        return 1

    ttl = HEADER_BY_SCOPE[args.scope] + PREFIXES + "\n" + "\n\n".join(blocks) + "\n"
    if args.apply:
        out_path.write_text(ttl, encoding="utf-8")
        print(f"[OK] wrote {out_path.name} ({len(pats)} 패턴, gap 0)")
    else:
        print(f"[DRY-RUN] → --apply 시 {out_path.name} 기록. 첫 패턴 미리보기:")
        print("\n".join(blocks[0].splitlines()[:14]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
