#!/usr/bin/env python3
"""Stage-4 exporter — PG she_catalog의 OWA→CWA L2 보강 37패턴 → canonical ABox TTL.

이번 세션의 SHE 보강(marker owacwa-l2tune/foodgas/ind-20260608)으로 PG `she_catalog`에 추가된
37 SHE 패턴을 온톨로지 ABox(she:SituationalHazardPattern)로 내보내 Fuseki/리즈너에 정합시킨다.

기존 data-team/05-enrichment/she-scripts/load_she_to_fuseki.py의 hand value-map은 stale(신규
코드 다수 미포함, 미매핑 silent skip) → 여기서는 **결정적 UPPER_SNAKE→PascalCase** + **TBox 존재
검증**(ontology-team scripts/gen_she_abox.py의 defined_facets 미러)로 대체한다.

출력: ontology-team/06-reasoning/ontology/kosha-instances-she-l2tune.ttl
사용: python export_she_catalog_to_abox.py [--apply]   (기본 dry-run; gap 0이어야 기록 가능)
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

import psycopg2
from rdflib import Graph, RDF, RDFS, OWL

HERE = Path(__file__).resolve()
ROOT = HERE.parents[3]  # export-scripts/ -> 04-ontology-export/ -> data-team/ -> repo root
ONT = ROOT / "ontology-team" / "06-reasoning" / "ontology"
sys.path.insert(0, str(ONT / "assembly"))
import manifest_source as MS  # noqa: E402

OUT = ONT / "kosha-instances-she-l2tune.ttl"
PG_DSN = "dbname=kosha user=kosha password=1229 host=localhost port=5432"
MARKERS = ["owacwa-l2tune-20260608", "owacwa-foodgas-20260608", "owacwa-ind-20260608"]

NS = {
    "ctx":   "https://cashtoss.info/ontology/risk/context#",
    "haz":   "https://cashtoss.info/ontology/risk/hazard#",
    "agent": "https://cashtoss.info/ontology/risk/agent#",
}
FACET_NS = tuple(NS.values())

# dim -> (she property local, prefix)
DIM_AXIS = {
    "work_activity":   ("hasWorkActivity",   "ctx"),
    "work_context":    ("hasWorkContext",    "ctx"),
    "hazardous_agent": ("hasHazardousAgent", "agent"),
    "accident_type":   ("hasAccidentType",   "haz"),
    "agent_state":     ("hasAgentState",     "ctx"),
    "ppe_state":       ("hasPPEState",       "ctx"),
    "environmental":   ("hasEnvironmental",  "ctx"),
    "temporal_stage":  ("hasTemporalStage",  "ctx"),
}
# OTHER -> Other{Axis} class (기존 컨벤션 보존). wc/at/ha의 OTHER는 OWL 미정의라 skip.
OTHER_CLASS = {
    "work_activity": "OtherActivity", "agent_state": "OtherAgentState",
    "ppe_state": "OtherPPEState", "environmental": "OtherEnvironmental",
    "temporal_stage": "OtherTemporal",
}
SKIP_OTHER = {"work_context", "accident_type", "hazardous_agent"}

PREFIXES = """# kosha-instances-she-l2tune.ttl — OWA→CWA L2 보강 SHE 패턴 ABox
# (AUTO-GENERATED by data-team/04-ontology-export/export-scripts/export_she_catalog_to_abox.py — 수동편집 금지)
# 소스: PG she_catalog WHERE source_prompt_hash IN (owacwa-l2tune/foodgas/ind-20260608)
@prefix risk:  <https://cashtoss.info/ontology/risk#> .
@prefix she:   <https://cashtoss.info/ontology/risk/situation#> .
@prefix sr:    <https://cashtoss.info/ontology/sr#> .
@prefix ctx:   <https://cashtoss.info/ontology/risk/context#> .
@prefix agent: <https://cashtoss.info/ontology/risk/agent#> .
@prefix haz:   <https://cashtoss.info/ontology/risk/hazard#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
"""


def snake_to_pascal(code: str) -> str:
    return "".join(seg.capitalize() for seg in code.split("_"))


def feature_iri(dim: str, value):
    if not value:
        return None
    if value == "OTHER":
        if dim in SKIP_OTHER:
            return None
        frag = OTHER_CLASS.get(dim)
        return f"{DIM_AXIS[dim][1]}:{frag}" if frag else None
    return f"{DIM_AXIS[dim][1]}:{snake_to_pascal(value)}"


def expand(curie: str) -> str:
    prefix, frag = curie.split(":", 1)
    return NS[prefix] + frag


def escape_ttl(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def defined_facets() -> set:
    """serving profile의 비-instances 파일에 정의된 haz/agent/ctx 클래스·개체 (gen_she_abox 미러)."""
    defined = set()
    for e in MS.by_profile("serving"):
        if "instances" in e["file"]:
            continue
        g = Graph()
        g.parse(str(ONT / e["file"]), format=("xml" if e["format"] == "xml" else "turtle"))
        for s in g.subjects(RDF.type, OWL.Class):
            defined.add(str(s))
        for s in g.subjects(RDF.type, OWL.NamedIndividual):
            defined.add(str(s))
        for s, _o in g.subject_objects(RDFS.subClassOf):
            defined.add(str(s))
    return defined


def fetch_patterns() -> list[dict]:
    conn = psycopg2.connect(PG_DSN)
    cur = conn.cursor()
    cur.execute(
        """
        SELECT c.she_id, c.name, c.features, c.visual_triggers, c.source_sr_ids,
               COALESCE(json_agg(DISTINCT m.ci_id) FILTER (WHERE m.ci_id IS NOT NULL), '[]'::json) AS ci_ids
        FROM she_catalog c
        LEFT JOIN she_ci_mapping m ON m.she_id = c.she_id
        WHERE c.source_prompt_hash = ANY(%s)
        GROUP BY c.she_id, c.name, c.features, c.visual_triggers, c.source_sr_ids
        ORDER BY c.she_id
        """,
        (MARKERS,),
    )
    rows = []
    for she_id, name, features, vts, srs, ci_ids in cur.fetchall():
        def _j(v, default):
            if v is None:
                return default
            return v if not isinstance(v, str) else json.loads(v)
        rows.append({
            "she_id": she_id, "name": name or "",
            "features": _j(features, {}), "visual_triggers": _j(vts, []),
            "source_sr_ids": _j(srs, []), "ci_ids": _j(ci_ids, []),
        })
    cur.close()
    conn.close()
    return rows


def vt_texts(vts, fallback: str) -> list[str]:
    out = []
    for item in vts or []:
        v = item.get("text") if isinstance(item, dict) else str(item)
        if v and v.strip():
            out.append(v.strip())
    return out or ([fallback] if fallback else [])


def she_block(p: dict):
    she_id = p["she_id"]
    lines = [f"she:{she_id} a she:SituationalHazardPattern ;"]
    if p["name"]:
        lines.append(f'    rdfs:label "{escape_ttl(p["name"])}"@ko ;')
    feats = []
    for dim, val in (p["features"] or {}).items():
        if dim not in DIM_AXIS:
            continue
        iri = feature_iri(dim, val)
        if iri is None:
            continue
        lines.append(f"    she:{DIM_AXIS[dim][0]} {iri} ;")
        feats.append(iri)
    for iri in sorted(set(feats)):
        lines.append(f"    risk:hasFeature {iri} ;")
    triggers = vt_texts(p["visual_triggers"], p["name"])
    tids = [f"VT-{she_id}-{i + 1}" for i in range(len(triggers))]
    for tid in tids:
        lines.append(f"    she:hasVisualTrigger she:{tid} ;")
    srs = [f"sr:{s}" for s in p["source_sr_ids"]]
    if srs:
        lines.append(f"    she:appliesSR {', '.join(srs)} .")
    else:
        lines[-1] = lines[-1].rstrip(" ;") + " ."
    blocks = ["\n".join(lines)]
    for tid, txt in zip(tids, triggers):
        blocks.append(f'she:{tid} a she:VisualTrigger ;\n    she:triggerText "{escape_ttl(txt)}"@ko .')
    return "\n\n".join(blocks), feats


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="파일 기록(기본 dry-run)")
    args = ap.parse_args()

    pats = fetch_patterns()
    blocks, used = [], set()
    for p in pats:
        block, feats = she_block(p)
        blocks.append(block)
        used.update(expand(f) for f in feats)

    defined = defined_facets()
    gaps = sorted(u for u in used if u.startswith(FACET_NS) and u not in defined)
    print(f"  패턴 {len(pats)} · 사용 facet IRI {len(used)} (TBox gap {len(gaps)})")
    if gaps:
        print("[FAIL] TBox에 정의 없는 facet 코드(gap):", file=sys.stderr)
        for g in gaps:
            print("   ", g, file=sys.stderr)
        return 1

    ttl = PREFIXES + "\n" + "\n\n".join(blocks) + "\n"
    if args.apply:
        OUT.write_text(ttl, encoding="utf-8")
        print(f"[OK] wrote {OUT.name} ({len(pats)} 패턴, gap 0)")
    else:
        print("[DRY-RUN] gap 0 → --apply로 기록 가능. 첫 패턴 미리보기:")
        print("\n".join(blocks[0].splitlines()[:14]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
