#!/usr/bin/env python3
"""SHE ABox 생성기 — data-team SHE 패턴(구버전 어휘)을 canonical로 마이그레이션해 온톨로지에 편입.

배경: data-team/05-enrichment/she-data/she-instances-v1.ttl 은 965 SHE 패턴 × 6축 맥락
(she:hasWorkContext/AgentState/EnvironmentalFactor/PPEState/TemporalStage/WorkActivity + accident/agent)을
완비하나, 2026-04 생성본이라 KOSHA-22 canonical 이전 어휘(haz:Crush/Cut/FallingObject/Slip/Ergonomic
/FoodContamination, agent:ArcFlash/Corrosion)를 쓴다. 또 온톨로지 manifest에 미등록이라 메인 추론
그래프(kosha-instances.ttl)엔 SHE 인스턴스가 0개였다.

본 생성기는 그 소스를 읽어 **migrate_vocab_to_kosha22 와 동일한 결정적 치환**(legacy→KOSHA-22)을 적용해
ontology-team/kosha-instances-she.ttl 을 생성한다(텍스트 치환 = 원본 포맷·맥락 보존, 코드만 현행화).
"온톨로지 설계가 정본, data-team 산출물은 그에 맞춰 migrate"(사용자 지침 2026-05-31) 원칙.

검증: 출력의 모든 haz/agent/ctx 코드가 현 온톨로지 정의 개체에 실재해야 한다(아니면 exit 1).
재현: 소스 갱신 시 재실행. data-team이 향후 canonical로 재생성하면 치환은 no-op이 된다.

사용: python scripts/gen_she_abox.py [--apply]   (기본 dry-run; --apply로 파일 기록)
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

from rdflib import Graph, RDF, RDFS, OWL, URIRef

ONT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ONT / "assembly"))
sys.path.insert(0, str(ONT / "scripts"))
import manifest_source as MS  # noqa: E402
import migrate_vocab_to_kosha22 as MIG  # noqa: E402

SRC = ONT.parents[2] / "data-team" / "05-enrichment" / "she-data" / "she-instances-v1.ttl"
OUT = ONT / "kosha-instances-she.ttl"
FACET_NS = ("https://cashtoss.info/ontology/risk/hazard#",
            "https://cashtoss.info/ontology/risk/agent#",
            "https://cashtoss.info/ontology/risk/context#")

HEADER = (
    "# kosha-instances-she.ttl — SHE 패턴 ABox (AUTO-GENERATED by scripts/gen_she_abox.py — 수동편집 금지)\n"
    "# 소스: data-team/05-enrichment/she-data/she-instances-v1.ttl (965 SHE 패턴 × 6축 맥락)\n"
    "# 변환: migrate_vocab_to_kosha22 결정적 치환으로 legacy 어휘 → KOSHA-22 canonical (코드만 현행화).\n"
    "# 재생성: python scripts/gen_she_abox.py --apply\n"
)


def canonicalize(text: str) -> str:
    for pat, repl, _label in MIG.build_patterns():
        text = pat.sub(repl, text)
    text = MIG.UPPER_PAT.sub(MIG._case_repl, text)
    return text


def defined_facets() -> set:
    """현 온톨로지(비-instances serving 파일)의 정의된 haz/agent/ctx 개체."""
    defined = set()
    for e in MS.by_profile("serving"):
        if "instances" in e["file"]:
            continue
        g = Graph()
        g.parse(str(ONT / e["file"]), format=("xml" if e["format"] == "xml" else "turtle"))
        for s in g.subjects(RDF.type, OWL.Class):
            defined.add(s)
        for s in g.subjects(RDF.type, OWL.NamedIndividual):
            defined.add(s)
        for s, _ in g.subject_objects(RDFS.subClassOf):
            defined.add(s)
    return defined


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="파일 기록(기본 dry-run)")
    args = ap.parse_args()

    if not SRC.exists():
        print(f"[FAIL] 소스 없음: {SRC}", file=sys.stderr)
        return 1
    raw = SRC.read_text(encoding="utf-8")
    migrated = canonicalize(raw)

    # 검증 1: 파싱
    gm = Graph()
    gm.parse(data=migrated, format="turtle")
    she = URIRef("https://cashtoss.info/ontology/risk/situation#SituationalHazardPattern")
    n_pat = sum(1 for _ in gm.subjects(RDF.type, she))

    # 검증 2: 모든 facet 코드가 현 온톨로지에 실재
    defined = defined_facets()
    used = {x for s, p, o in gm for x in (s, o)
            if isinstance(x, URIRef) and str(x).startswith(FACET_NS)}
    gaps = sorted((u for u in used if u not in defined), key=str)
    print(f"  소스 {len(raw):,}B → migrated {len(migrated):,}B")
    print(f"  SHE 패턴 {n_pat} · triple {len(gm):,} · facet 코드 {len(used)} (gap {len(gaps)})")
    if gaps:
        print("[FAIL] 현 온톨로지에 없는 코드(gap):", file=sys.stderr)
        for g_ in gaps[:30]:
            print("   ", g_, file=sys.stderr)
        return 1

    if args.apply:
        OUT.write_text(HEADER + migrated, encoding="utf-8")
        print(f"[OK] wrote {OUT.name} ({n_pat} SHE 패턴, {len(gm):,} triple, gap 0)")
    else:
        print("[DRY-RUN] --apply로 기록. gap 0 → 기록 가능.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
